import 'package:flutter/material.dart';

final List<Map<String, dynamic>> wiraData = [
  {
    'id': 0,
    'judul': 'WIRAKU',
    'name': 'Optimus Prime',
    'imagePath': 'assets/wira-01.png',
    'description1': 'Sang Pemimpin Autobots',
    'description2': 'dengan kebijaksanaan yang menginspirasi',
    'rating': 5,
    'themeColor': Colors.blue,
    'wikiUrl': 'https://en.wikipedia.org/wiki/Optimus_Prime',
  },
  {
    'id': 1,
    'judul': 'WIRAKU',
    'name': 'Iron Man',
    'imagePath': 'assets/wira-02.png',
    'description1': 'Sang Jenius, Triliuner, Filantropis',
    'description2': 'dengan baju zirah bertenaga tinggi',
    'rating': 4,
    'themeColor': Colors.amber,
    'wikiUrl': 'https://en.wikipedia.org/wiki/Iron_Man',
  },
  {
    'id': 2,
    'judul': 'WIRAKU',
    'name': 'Spider-Man',
    'imagePath': 'assets/wira-03.png',
    'description1': 'Sang Pahlawan Super yang Ramah',
    'description2': 'dengan kekuatan laba-labanya',
    'rating': 4,
    'themeColor': Colors.redAccent,
    'wikiUrl': 'https://en.wikipedia.org/wiki/Spider-Man',
  },
  {
    'id': 3,
    'judul': 'WIRAKU',
    'name': 'Doctor Strange',
    'imagePath': 'assets/wira-04.png',
    'description1': 'Sang Penguasa Seni Mistis',
    'description2': 'dengan kemampuan untuk memanipulasi ruang dan waktu',
    'rating': 4,
    'themeColor': Colors.orangeAccent,
    'wikiUrl': 'https://en.wikipedia.org/wiki/Doctor_Strange',
  },
  {
    'id': 4,
    'judul': 'WIRAKU',
    'name': 'Batman',
    'imagePath': 'assets/wira-05.png',
    'description1': 'Sang Detektif Triliuner',
    'description2': 'dengan kejeniusannya di Gotham City',
    'rating': 4,
    'themeColor': Colors.grey,
    'wikiUrl': 'https://en.wikipedia.org/wiki/Batman',
  },
];
